version: '3.8'

services:
  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app:/var/www/html
    expose:
      - "9000"
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root # Giữ lại dòng này
      MYSQL_DATABASE: users
      # Xóa hai dòng sau:
      # MYSQL_USER: root
      # MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 0
      PHP_UPLOAD_MAX_FILESIZE: 2M # Thêm dòng này
    depends_on:
      - db
    networks:
      - app-network
    extra_hosts:
      - "db:127.0.0.1"

networks:
  app-network:
    driver: bridge

volumes:
  db_data: