version: '3.8'

services:
  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .  # Quan trọng: context là thư mục gốc của dự án
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app:/var/www/html
    expose:
      - "9000"
    networks:
      - app-network

  db:
    image: mysql:5.7 # Hoặc phiên bản MySQL bạn đang dùng
    environment:
      MYSQL_ROOT_PASSWORD: root # Thay đổi nếu bạn muốn đặt mật khẩu root khác
      MYSQL_DATABASE: users # Lấy từ file config của bạn
      MYSQL_USER: root # Lấy từ file config của bạn
      MYSQL_PASSWORD: "" # Lấy từ file config của bạn (đang trống)
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root # Sử dụng mật khẩu root của MySQL
      PMA_ARBITRARY: 0
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: